server {
    listen          80; #HTTP port
    server_name     localhost;

    location / { # defines behavior for requets to `/` (root path)
        root /usr/share/nginx/html;
        index index.html; #  default file to serve
    }

    error_page  404              /errors/404.html;
}